alumnusb_system/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from . import views as accounts_views
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
	url(r'^personal_data/(?P<username>[\w.@+-]+)/$', accounts_views.user_data, name = 'user_data'),

    url(r'^personal_data/edit/(?P<username>[\w.@+-]+)/$', accounts_views.edit_user_data, name = 'edit_user_data'),
    url(r'^personal_data/edit_picture/(?P<username>[\w.@+-]+)/$', accounts_views.edit_user_picture, name = 'edit_user_picture'),

	url(r'^login/', LoginView.as_view(), name = 'login_url'),

	url(r'^register/', accounts_views.registerView, name = "register_url"),

	url(r'^logout/', LogoutView.as_view(next_page="home"), name = "logout")
]

alumnusb_system/alumnusb_system/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
from django.contrib.auth import views as auth_views

from accounts import views as accounts_views
from main import views
from CSV.views import profile_upload

# Por favor tratar con carino estos url
urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS

    url(r'^admin/', admin.site.urls),
    path('upload-csv/', profile_upload, name="profile_upload"),

    url(r'^$', views.index, name='home'),
    url(r'^dashboard/(?P<username>[\w.@+-]+)/$', views.dashboard, name = 'dashboard'),

    path('accounts/', include('accounts.urls')),

    url(r'^prueba_logros/(?P<username>[\w.@+-]+)/$', views.achievements, name = 'achievements'),
    url(r'^my_stats/(?P<username>[\w.@+-]+)/$', views.user_stats, name = 'my_stats'),
    url(r'^my_achievements/(?P<username>[\w.@+-]+)/$', views.achievements, name = 'my_achievs'),

    # View para pasarle la informacion a los graficos
    path('resume-chart/', views.resume_chart, name='resume-chart'),
]

alumnusb_system/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from accounts.utils import CountryField
from accounts.utils import CampusChoice
from accounts.utils import UndergraduateDegreeChoice
from django.utils import timezone
from datetime import date

class Profile_Picture(models.Model):
	Picture = models.ImageField(upload_to='static/prof_img/')

class User_information(models.Model):
	First_name = models.CharField(max_length=30, default='-')
	Middle_name = models.CharField(max_length=30, default='-')
	Last_name = models.CharField(max_length=30, default='-')
	Mailing_city = models.CharField(max_length=30, default='-')
	Mailing_state = models.CharField(max_length=30, default='-')
	USB_alumn = models.BooleanField(default=False)
	Codigo_Alumn_USB = models.CharField(max_length=30, default='-')
	Mailing_country = CountryField()
	Email = models.EmailField(max_length=60, unique=True)
	Mobile = models.CharField(max_length=30, default='-')
	Cohorte = models.IntegerField(default=0)
	Birthdate = models.DateField()
	Age = models.IntegerField(default=0)
	Undergrad_degree = models.CharField(max_length=3, choices=[(tag.name, tag.value) for tag in UndergraduateDegreeChoice])
	Graduate_degree = models.CharField(max_length=60)
	Carnet = models.IntegerField(default=0)
	USB_undergrad_campus = models.CharField(max_length=2, choices=[(tag.name, tag.value) for tag in CampusChoice])
	Graduate_campus = models.CharField(max_length=30, default='-')
	Work_email = models.EmailField(max_length=60)
	Workplace = models.CharField(max_length=30, default='-')
	Donor = models.BooleanField(default=False)
	Social_networks = models.CharField(max_length=50, default='-')
	Twitter_account = models.CharField(max_length=60,default='-')
	Instagram_account = models.CharField(max_length=60, default='-')
	Picture = models.ForeignKey(Profile_Picture, on_delete=models.SET_NULL, null=True)

	def __str__(self):
		return self.Email

class User_stats(models.Model):
	Email = models.EmailField(max_length=60, unique=True)
	Average_gift = models.FloatField()
	Largest_gift = models.FloatField()
	Smallest_gift = models.FloatField()
	Total_gifts = models.FloatField()
	Best_gift_year_total = models.FloatField()
	Best_gift_year = models.IntegerField(null=True)
	First_gift_date = models.DateField(null=True)
	Last_gift_date = models.DateField(null=True)
	Total_number_of_gifts = models.IntegerField()

	def __str__(self):
		return self.Email

class Achievements(models.Model):
	Name = models.CharField(primary_key=True, max_length=50)
	Description = models.CharField(max_length=200)
	Picture = models.ImageField(default='static/achiev_img/C.png', upload_to='static/achiev_img/') 
	Level = models.IntegerField(default=1)
	

class User_Achievements(models.Model):
	Owner = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
	Achievement = models.ForeignKey(Achievements,on_delete=models.CASCADE,default=None)
	Date = models.DateField(default=timezone.now)

	# Falta definir un __str__

class Message(models.Model):
	Page = models.CharField(max_length=30, primary_key=True)
	Title = models.CharField(max_length=50,default=' ')
	Txt = models.CharField(max_length=2000,default=' ')

alumnusb_system/templates/achievements.html
<!DOCTYPE html>
<html>
<head>
	<title>pruebas</title>
</head>
<body  bgcolor=yellow>
	<h1>
	<p> {{ user.username }} </p>
	<p> {{ ach1 }} </p>
	<p> {{ ach2 }} </p>
	<p> {{ ach3 }} </p>
	<p> {{ ach4 }} </p>
	<p> {{ ach5 }} </p>
	<p> hola </p>
	</h1>
</body>
</html>

alumnusb_system/templates/achievements2.html
<!DOCTYPE html>
<html>
<head>
	<title>pruebas</title>
</head>
<body>
	<h1>hola</h1>
	{% for p in achievs %}
		<!--
			p[0]: achiev object
			p[1]: date (maybe null)
			p[2]: achievement achieved
			p[4]: img url
		-->
		<h1>{{p.0.Name}}</h1>
		<h4>{{p.0.Description}}</h4>
		<h5>{{p.0.Picture.url}}</h5>
		<img src="{{ p.3 }}">

		{% if p.2 %}
			{{ p.1 }}
			<h1>got it</h1>
		{% endif %}
		
	{% endfor %}
</body>
</html>

alumnusb_system/templates/base.html
{% load static %}
{% load  bootstrap4  %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}AlumnUSB{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
    <link rel="icon" href="/static/img/alumnusb_logo.jpg">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">

    <!-- Custom fonts for this theme -->
    <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    
    {% block stylesheet %}{% endblock %}
    <!-- Theme landing page -->
    <link rel="stylesheet" href="{% static 'css/freelancer.css' %}">
  </head>
  
  <body id="page-top">
    <div id="megadiv"></div>
    <!--<div style="height:50px;"></div>-->
    
    {% block body %}
      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg bg-black text-uppercase fixed-top" id="mainNav">
        <div class="container">
          <a class="navbar-brand js-scroll-trigger" href="{% url 'home' %}">AlumnUSB</a>
         
          <button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            {% if user.is_authenticated %}
              <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ user.username }}
                  </a>
                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                    <a class="dropdown-item" href="{% url 'user_data' user.username %}">Mi perfil</a>
                    <a class="dropdown-item" href="{% url 'dashboard' user.username %}">Mis logros</a>

                    {% if user.is_superuser %}
                    <div class="dropdown-divider"></div>
                      <a class="dropdown-item" href="{% url 'profile_upload' %}">Cargar CSV</a>
                    {% endif %}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'logout' %}">Salir</a>
                  </div>
                </li>
              </ul>
            {% else %}
            <ul class="navbar-nav ml-auto">
              <li class="nav-item mx-0 mx-lg-1">
                <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="https://alumnusb.org/">AlumnUSB</a>
              </li>
              <li class="nav-item mx-0 mx-lg-1">
                <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#portfolio">Logros</a>
              </li>
              <li class="nav-item mx-0 mx-lg-1">
                <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" href="#about">info</a>
              </li>
            </ul>
            
            <form class=" nav-item form-inline ml-auto">
              <a href="{% url 'login_url' %}" class="btn btn-primary rounded ml-2">Iniciar</a>
              <a href="{% url 'register_url' %}" class="btn btn-primary rounded ml-2">Registrarme</a>
            </form>
            {% endif %}
          </div>
        </div>
      </nav>

      {% block content %}
      {% endblock %}

    <!-- Footer -->

    {% block footer %}
      <footer class="footer text-center bg-third" style = "width: 100%;">
        <div class="container">
          <div class="row">

            <!-- Footer Location -->
            <div class="col-lg-4 mb-5 mb-lg-0">
              <h4 class="text-uppercase mb-4 text-black">Ubicación</h4>
              <p class="lead mb-0 text-black">Massachusetts, USA</p>
            </div>

            <!-- Footer Social Icons -->
            <div class="col-lg-4 mb-5 mb-lg-0">
              <h4 class="text-uppercase mb-4 text-black">Contacto</h4>
              <a class="btn btn-outline-dark btn-social mx-1" href="https://www.instagram.com/alumn_usb/">
                <i class="fab fa-fw fa-instagram"></i>
              </a>
              <a class="btn btn-outline-dark btn-social mx-1" href="https://twitter.com/alumn_usb/">
                <i class="fab fa-fw fa-twitter"></i>
              </a>
              <a class="btn btn-outline-dark btn-social mx-1" href="https://facebook.com/alumnusb/">
                <i class="fab fa-fw fa-facebook-f"></i>
              </a>
              <a class="btn btn-outline-dark btn-social mx-1" href="https://www.youtube.com/c/alumnusb/">
                <i class="fab fa-fw fa-youtube"></i>
              </a>
              <a class="btn btn-outline-dark btn-social mx-1" href="https://www.linkedin.com/company/alumnusb/">
                <i class="fab fa-fw fa-linkedin-in"></i>
              </a>
            </div>

            <!-- Footer About Text -->
            <div class="col-lg-4">
              <h4 class="text-uppercase mb-4 text-black">Info</h4>
              <p class="lead mb-0 text-black">Este proyecto cumple con la alcanzabilidad pautada para la materia de Sistemas de información, para crear la primera versión beta. </p>
            </div>

          </div>
        </div>
      </footer>
    {% endblock footer %}
    
    <!-- Copyright Section -->
    
    {% block copyright %}
      <section class="copyright py-4 text-center text-white bg-black">
        <div class="container">
          <small>Copyright &copy; Alumnification 2020</small>
        </div>
      </section>
    {% endblock copyright %}
    
    {% endblock body %}
    
  <!-- Bootstrap core JavaScript -->
  <script src="{%static  'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Plugin JavaScript -->
  <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static 'js/freelancer.min.js' %}"></script>
  </body>
</html>

alumnusb_system/templates/edit_user_data.html
{% extends 'user_data.html' %}

{% load widget_tweaks %}

{% block title %} Edit User Data {% endblock %}

{% block content %}
<div class="masthead">
  <div class="container bg-white d-flex flex-column rounded shadow-lg">
    <h1 class="masthead-heading text-uppercase text-center text-secondary mb-0 mt-5">Editar información de usuario</h1>
    
    <!-- Icon Divider -->
    <div class="divider-custom">
      <div class="divider-custom-line"></div>
      <div class="divider-custom-icon">
        <i class="fas fa-star"></i>
      </div>
      <div class="divider-custom-line"></div>
    </div>

    <div class="row">
      <div class="col-lg-8 mx-auto">
        <form method="POST">

          {% csrf_token %}
          {% for field in form %}
            <div class="fieldWrapper">
              <div class="form-group floating-label-form-group-edit controls mb-0 pb-2">
                {{ field.label_tag }} 
                
                {{ field }}
                
                {% if field.help_text %}
                  <p class="help-block">{{ field.help_text|safe }}</p>
                {% endif %}
                <strong class="help-block text-danger">{{ field.errors }}</strong>
              </div>
            </div>
          {% endfor %}

          <div class="form-group text-center mt-3 mb-3">
            <button type="submit" class="btn btn-outline-al btn-xl">Save</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content%}

alumnusb_system/templates/edit_user_picture.html
<!DOCTYPE html>
<html>
<head>
	<title>hola</title>
</head>
<body>
	<h1>hola</h1>
    <form method="POST"> 
    	{% csrf_token %}
    	{{ form.as_p }}
    	<button type="submit" class="btn btn-outline-al btn-xl">Save</button>
    </form>
</body>
</html>

alumnusb_system/templates/prof_pic_form_modal.html
{% load static %}
{% load widget_tweaks %}
<!--
    Variables required by this template:
        mid: modal id
        imgs: available profile pics
        currentImg: current selected img
        picform: form to send
-->
<div class="portfolio-modal modal fade" id="{{mid}}" tabindex="-1" role="dialog" aria-labelledby="portfolioModal2Label" aria-hidden="true">
    <div class="modal-dialog modal-xl" role="document">
      <div class="modal-content">
        <button type="button" class="close text-warning" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            <i class="fas fa-times"></i>
          </span>
        </button>

        <div class="modal-body text-center">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col-lg-8">
                <!-- Portfolio Modal - Title -->
                <h2 class="text-secondary text-uppercase mb-0">Escoge una</h2>
                <!-- Icon Divider -->
                <div class="divider-custom">
                  <div class="divider-custom-line"></div>
                  <div class="divider-custom-icon">
                    <i class="fas fa-star"></i>
                  </div>
                  <div class="divider-custom-line"></div>
                </div>
                

                <div class="row my-2">
                    {% for img in imgs %}
                    <div class="col-lg-3 col-xl-3 col-sm-6 mb-2">
                        <div class="btn-light btn prof-pic-btn" data-imgid="{{img.0.id}}" id="imgbtn{{img.0.id}}">
                            <img class="img-fluid rounded" src="{{img.1}}" alt="" id="img{{img.0.id}}"data-imgid="{{img.0.id}}">
                        </div>
                    </div>
                    {% empty %}
                    <small>(No hay imágenes para seleccionar)</small>
                    {% endfor %}
                </div>
                <form id="update-pic-form" action="POST" novalidate data-url="{% url 'edit_user_picture' user.username %}">
                    {% csrf_token %}
                    {{form.Pic_id|attr:"hidden:true"|attr:"id:selected-img"}}
                    <button class="btn btn-warning text-light" id="update-pic-btn" type="submit">
                        Aceptar
                    </button>
                </form>
                <div class="alert alert-success my-2 fade in alert-dismissible show d-none" id="success-alert">
                    <div>
                        Su imagen se ha actualizado exitosamente
                    </div>
                </div>
                <div class="alert alert-info my-2 fade in alert-dismissible show d-none" id="info-alert">
                    <div>
                        Debe escoger una imagen
                    </div>
                </div>
                <div class="alert alert-danger my-2 fade in alert-dismissible show d-none" id="fail-alert">
                    <div>
                        Su imagen de perfil no pudo ser actualizada
                    </div>
                </div>
                <!-- Portfolio Modal - Text -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<!-- Bootstrap core JavaScript -->
<script src="{%static  'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Plugin JavaScript -->
<script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
<!--Custom variables and scripts-->
<script>
    var userImg = {{currentImg}};
</script>
<script src="{% static 'js/select_prof_pic.js' %}"></script>

alumnusb_system/templates/user_data.html
{% extends 'base.html'%}
{% load static %}

{% block stylesheet %}
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" href=" {% static 'css/user_data.css' %} ">

{% endblock stylesheet %}

{% block content %}
<div style="height: 5rem"></div>
<div class="container emp-profile horizontal-align shadow-lg">
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-img">
                            {% if pic.1 %}
                                <img src="{{pic.0}}" class="img-fluid" data-imgid="{{pic.2}}" id="profile-pic">
                            {% else %}
                                <img src=" {% static 'img/default-user.png'  %} " alt="" class="img-fluid" 
                                data-imgid="{{pic.2}}" id="profile-pic"/>
                            {% endif %}
                            <div class="file btn btn-lg btn-primary h-100 mb-5" data-target="#prof-pic-form" data-toggle="modal">
                                Cambiar imagen.
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        {{prof_pic_mid}}
                        <div class="profile-head">
                                    <h5>
                                        {{ User_information.First_name}}  
                                        {{ User_information.Middle_name }}
                                        {{ User_information.Last_name}} 
                                        
                                    </h5>
                                    <h6>
                                        {{ User_information.get_Undergrad_degree_display }}
                                    </h6>
                                    {% if User_information.Donor == 1 %}
                                    <p class="proile-rating">Donor &#127775; </p>
                                    {% endif %}
                                    {% if User_information.USB_alumn == 1%}
                                    <p> USB Alumn &#127775; </p>
                                    {% endif%}
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="" role="tab" aria-controls="home" aria-selected="true">About</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <a href="{% url 'edit_user_data' user.username %}" class="btn-primary rounded" id="edit-profile"> <strong>Edit Profile</strong> </a>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="profile-work">
                            <strong>SOCIAL MEDIA:</strong>
                            <ul>
                                <li>Twitter: {{User_information.Twitter_account}} </li>
                                <li>Instagram: {{User_information.Instagram_account}} </li>
                            </ul>
                            
                            <strong>CONTACT INFO:</strong>
                            <ul>
                                <li>Mailing city: {{ User_information.Mailing_city}}</li>
                                <li>Mailing state: {{ User_information.Mailing_state}}</li>
                                <li>Mailing country: {{ User_information.get_Mailing_country_display }}</li>
                                <li>Mobile number: {{ User_information.Mobile }}</li>
                                <li>Email: {{User_information.Email}} </li>
                                <li>Work Email: {{User_information.Work_email}} </li>
                                
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="tab-content profile-tab" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label><strong> Birth date: </strong></label>
                                            </div>
                                            <div class="col-md-6">
                                                <p> {{User_information.Birthdate}} </p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label><strong> Cohorte: </strong></label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{User_information.Cohorte}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label><strong> Carnet: </strong></label>
                                            </div>
                                            <div class="col-md-6">
                                                <p>{{User_information.Carnet}}</p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label> <strong>Undergraduate Campus: </strong> </label>
                                            </div>
                                            <div class="col-md-6">
                                                <p> {{User_information.get_USB_undergrad_campus_display }} </p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label><strong> Graduate Degree: </strong></label>
                                            </div>
                                            <div class="col-md-6">
                                                <p> {{User_information.Graduate_degree}} </p>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-6">
                                                <label> <strong> Graduate Campus: </strong> </label>
                                            </div>
                                            <div class="col-md-6">
                                                <p> {{User_information.Graduate_campus}} </p>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-md-6">
                                                <label> <strong> Workplace: </strong> </label>
                                            </div>
                                            <div class="col-md-6">
                                                <p> {{User_information.Workplace}} </p>
                                            </div>
                                        </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% include 'prof_pic_form_modal.html' with mid="prof-pic-form" imgs=prof_pics currentImg=pic.2 picform=form%}
                


        </div>
        {% endblock content %}